### ISSUE TITLE
[📍Task Card] TDD

### ISSUE THREAD

**Issue by dltmddus1998** [3rd-wanted-pre-onboarding-teamA/gameDuo-Wanted-A#20]
### **ISSUE**

- Group: `A Team`
- Type: `TDD`
- Detail: Test Case Code

### **TODO**

- [ ] 유저 측 기능 테스트 코드 작성하기
- [ ] 보스레이드 상태 조회 측 기능 테스트 코드 작성하기
- [ ] 보스레이드 랭킹 기능 테스트 코드 작성하기
- [ ] 보스레이드 시작 및 종료 기능 테스트 코드 작성하기

### **Labels**

- Estimated time: `E: 3h`
- Group : `A Team`
- Urgency: `High`
