### ISSUE TITLE
[📍Task Card] Refactoring

### ISSUE THREAD

**Issue by dltmddus1998** [3rd-wanted-pre-onboarding-teamA/gameDuo-Wanted-A#24]
### **ISSUE**

- Group: `A Team`
- Type: `Refactoring`
- Detail: 기능 리팩토링

### **TODO**

- [ ] 유저 측 기능 refactoring
- [ ] 보스레이드 상태 조회 측 기능 refactoring
- [ ] 보스레이드 랭킹 기능 refactoring
- [ ] 보스레이드 시작 및 종료 기능 refactoring

### **Labels**

- Estimated time: `E: 3h`
- Group : `A Team`
- Urgency: `High`
